steps:
  # 1. Build da imagem Docker usando Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/project-fefc6425-3e86-4253-b76/jcevolution/app:$COMMIT_SHA', '.']

  # 2. Push para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/project-fefc6425-3e86-4253-b76/jcevolution/app:$COMMIT_SHA']

  # 3. Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jcevolution-app'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/project-fefc6425-3e86-4253-b76/jcevolution/app:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'southamerica-east1-docker.pkg.dev/project-fefc6425-3e86-4253-b76/jcevolution/app:$COMMIT_SHA'
  
